/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface SuratData {
  id: string;
  number: number;
  name: string;
  totalAyat: number;
  type: 'Makkiyah' | 'Madaniyah';
}

export const QURAN_SURAHS: SuratData[] = [
  { id: "SR001", number: 1, name: "Al-Fatihah", totalAyat: 7, type: "Makkiyah" },
  { id: "SR002", number: 2, name: "Al-Baqarah", totalAyat: 286, type: "Madaniyah" },
  { id: "SR003", number: 3, name: "Ali 'Imran", totalAyat: 200, type: "Madaniyah" },
  { id: "SR004", number: 4, name: "An-Nisa'", totalAyat: 176, type: "Madaniyah" },
  { id: "SR005", number: 5, name: "Al-Ma'idah", totalAyat: 120, type: "Madaniyah" },
  { id: "SR006", number: 6, name: "Al-An'am", totalAyat: 165, type: "Makkiyah" },
  { id: "SR007", number: 7, name: "Al-A'raf", totalAyat: 206, type: "Makkiyah" },
  { id: "SR008", number: 8, name: "Al-Anfal", totalAyat: 75, type: "Madaniyah" },
  { id: "SR009", number: 9, name: "At-Tawbah", totalAyat: 129, type: "Madaniyah" },
  { id: "SR010", number: 10, name: "Yunus", totalAyat: 109, type: "Makkiyah" },
  { id: "SR011", number: 11, name: "Hud", totalAyat: 123, type: "Makkiyah" },
  { id: "SR012", number: 12, name: "Yusuf", totalAyat: 111, type: "Makkiyah" },
  { id: "SR013", number: 13, name: "Ar-Ra'd", totalAyat: 43, type: "Madaniyah" },
  { id: "SR014", number: 14, name: "Ibrahim", totalAyat: 52, type: "Makkiyah" },
  { id: "SR015", number: 15, name: "Al-Hijr", totalAyat: 99, type: "Makkiyah" },
  { id: "SR016", number: 16, name: "An-Nahl", totalAyat: 128, type: "Makkiyah" },
  { id: "SR017", number: 17, name: "Al-Isra'", totalAyat: 111, type: "Makkiyah" },
  { id: "SR018", number: 18, name: "Al-Kahf", totalAyat: 110, type: "Makkiyah" },
  { id: "SR019", number: 19, name: "Maryam", totalAyat: 98, type: "Makkiyah" },
  { id: "SR020", number: 20, name: "Taha", totalAyat: 135, type: "Makkiyah" },
  { id: "SR021", number: 21, name: "Al-Anbiya'", totalAyat: 112, type: "Makkiyah" },
  { id: "SR022", number: 22, name: "Al-Hajj", totalAyat: 78, type: "Madaniyah" },
  { id: "SR023", number: 23, name: "Al-Mu'minun", totalAyat: 118, type: "Makkiyah" },
  { id: "SR024", number: 24, name: "An-Nur", totalAyat: 64, type: "Madaniyah" },
  { id: "SR025", number: 25, name: "Al-Furqan", totalAyat: 77, type: "Makkiyah" },
  { id: "SR026", number: 26, name: "Ash-Shu'ara'", totalAyat: 227, type: "Makkiyah" },
  { id: "SR027", number: 27, name: "An-Naml", totalAyat: 93, type: "Makkiyah" },
  { id: "SR028", number: 28, name: "Al-Qasas", totalAyat: 88, type: "Makkiyah" },
  { id: "SR029", number: 29, name: "Al-Ankabut", totalAyat: 69, type: "Makkiyah" },
  { id: "SR030", number: 30, name: "Ar-Rum", totalAyat: 60, type: "Makkiyah" },
  { id: "SR031", number: 31, name: "Luqman", totalAyat: 34, type: "Makkiyah" },
  { id: "SR032", number: 32, name: "As-Sajdah", totalAyat: 30, type: "Makkiyah" },
  { id: "SR033", number: 33, name: "Al-Ahzab", totalAyat: 73, type: "Madaniyah" },
  { id: "SR034", number: 34, name: "Saba'", totalAyat: 54, type: "Makkiyah" },
  { id: "SR035", number: 35, name: "Fatir", totalAyat: 45, type: "Makkiyah" },
  { id: "SR036", number: 36, name: "Ya-Sin", totalAyat: 83, type: "Makkiyah" },
  { id: "SR037", number: 37, name: "As-Saffat", totalAyat: 182, type: "Makkiyah" },
  { id: "SR038", number: 38, name: "Sad", totalAyat: 88, type: "Makkiyah" },
  { id: "SR039", number: 39, name: "Az-Zumar", totalAyat: 75, type: "Makkiyah" },
  { id: "SR040", number: 40, name: "Ghafir", totalAyat: 85, type: "Makkiyah" },
  { id: "SR041", number: 41, name: "Fussilat", totalAyat: 54, type: "Makkiyah" },
  { id: "SR042", number: 42, name: "Ash-Shura", totalAyat: 53, type: "Makkiyah" },
  { id: "SR043", number: 43, name: "Az-Zukhruf", totalAyat: 89, type: "Makkiyah" },
  { id: "SR044", number: 44, name: "Ad-Dukhan", totalAyat: 59, type: "Makkiyah" },
  { id: "SR045", number: 45, name: "Al-Jathiyah", totalAyat: 37, type: "Makkiyah" },
  { id: "SR046", number: 46, name: "Al-Ahqaf", totalAyat: 35, type: "Makkiyah" },
  { id: "SR047", number: 47, name: "Muhammad", totalAyat: 38, type: "Madaniyah" },
  { id: "SR048", number: 48, name: "Al-Fath", totalAyat: 29, type: "Madaniyah" },
  { id: "SR049", number: 49, name: "Al-Hujurat", totalAyat: 18, type: "Madaniyah" },
  { id: "SR050", number: 50, name: "Qaf", totalAyat: 45, type: "Makkiyah" },
  { id: "SR051", number: 51, name: "Adh-Dhariyat", totalAyat: 60, type: "Makkiyah" },
  { id: "SR052", number: 52, name: "At-Tur", totalAyat: 49, type: "Makkiyah" },
  { id: "SR053", number: 53, name: "An-Najm", totalAyat: 62, type: "Makkiyah" },
  { id: "SR054", number: 54, name: "Al-Qamar", totalAyat: 55, type: "Makkiyah" },
  { id: "SR055", number: 55, name: "Ar-Rahman", totalAyat: 78, type: "Madaniyah" },
  { id: "SR056", number: 56, name: "Al-Waqi'ah", totalAyat: 96, type: "Makkiyah" },
  { id: "SR057", number: 57, name: "Al-Hadid", totalAyat: 29, type: "Madaniyah" },
  { id: "SR058", number: 58, name: "Al-Mujadilah", totalAyat: 22, type: "Madaniyah" },
  { id: "SR059", number: 59, name: "Al-Hashr", totalAyat: 24, type: "Madaniyah" },
  { id: "SR060", number: 60, name: "Al-Mumtahanah", totalAyat: 13, type: "Madaniyah" },
  { id: "SR061", number: 61, name: "As-Saff", totalAyat: 14, type: "Madaniyah" },
  { id: "SR062", number: 62, name: "Al-Jumu'ah", totalAyat: 11, type: "Madaniyah" },
  { id: "SR063", number: 63, name: "Al-Munafiqun", totalAyat: 11, type: "Madaniyah" },
  { id: "SR064", number: 64, name: "At-Taghabun", totalAyat: 18, type: "Madaniyah" },
  { id: "SR065", number: 65, name: "At-Talaq", totalAyat: 12, type: "Madaniyah" },
  { id: "SR066", number: 66, name: "At-Tahrim", totalAyat: 12, type: "Madaniyah" },
  { id: "SR067", number: 67, name: "Al-Mulk", totalAyat: 30, type: "Makkiyah" },
  { id: "SR068", number: 68, name: "Al-Qalam", totalAyat: 52, type: "Makkiyah" },
  { id: "SR069", number: 69, name: "Al-Haqqah", totalAyat: 52, type: "Makkiyah" },
  { id: "SR070", number: 70, name: "Al-Ma'arij", totalAyat: 44, type: "Makkiyah" },
  { id: "SR071", number: 71, name: "Nuh", totalAyat: 28, type: "Makkiyah" },
  { id: "SR072", number: 72, name: "Al-Jinn", totalAyat: 28, type: "Makkiyah" },
  { id: "SR073", number: 73, name: "Al-Muzzammil", totalAyat: 20, type: "Makkiyah" },
  { id: "SR074", number: 74, name: "Al-Muddaththir", totalAyat: 56, type: "Makkiyah" },
  { id: "SR075", number: 75, name: "Al-Qiyamah", totalAyat: 40, type: "Makkiyah" },
  { id: "SR076", number: 76, name: "Al-Insan", totalAyat: 31, type: "Madaniyah" },
  { id: "SR077", number: 77, name: "Al-Mursalat", totalAyat: 50, type: "Makkiyah" },
  { id: "SR078", number: 78, name: "An-Naba'", totalAyat: 40, type: "Makkiyah" },
  { id: "SR079", number: 79, name: "An-Nazi'at", totalAyat: 46, type: "Makkiyah" },
  { id: "SR080", number: 80, name: "'Abasa", totalAyat: 42, type: "Makkiyah" },
  { id: "SR081", number: 81, name: "At-Takwir", totalAyat: 29, type: "Makkiyah" },
  { id: "SR082", number: 82, name: "Al-Infitar", totalAyat: 19, type: "Makkiyah" },
  { id: "SR083", number: 83, name: "Al-Mutaffifin", totalAyat: 36, type: "Makkiyah" },
  { id: "SR084", number: 84, name: "Al-Inshiqaq", totalAyat: 25, type: "Makkiyah" },
  { id: "SR085", number: 85, name: "Al-Buruj", totalAyat: 22, type: "Makkiyah" },
  { id: "SR086", number: 86, name: "At-Tariq", totalAyat: 17, type: "Makkiyah" },
  { id: "SR087", number: 87, name: "Al-A'la", totalAyat: 19, type: "Makkiyah" },
  { id: "SR088", number: 88, name: "Al-Ghashiyah", totalAyat: 26, type: "Makkiyah" },
  { id: "SR089", number: 89, name: "Al-Fajr", totalAyat: 30, type: "Makkiyah" },
  { id: "SR090", number: 90, name: "Al-Balad", totalAyat: 20, type: "Makkiyah" },
  { id: "SR091", number: 91, name: "Ash-Shams", totalAyat: 15, type: "Makkiyah" },
  { id: "SR092", number: 92, name: "Al-Layl", totalAyat: 21, type: "Makkiyah" },
  { id: "SR093", number: 93, name: "Ad-Duha", totalAyat: 11, type: "Makkiyah" },
  { id: "SR094", number: 94, name: "Ash-Sharh", totalAyat: 8, type: "Makkiyah" },
  { id: "SR095", number: 95, name: "At-Tin", totalAyat: 8, type: "Makkiyah" },
  { id: "SR096", number: 96, name: "Al-Alaq", totalAyat: 19, type: "Makkiyah" },
  { id: "SR097", number: 97, name: "Al-Qadr", totalAyat: 5, type: "Makkiyah" },
  { id: "SR098", number: 98, name: "Al-Bayyinah", totalAyat: 8, type: "Madaniyah" },
  { id: "SR099", number: 99, name: "Az-Zalzalah", totalAyat: 8, type: "Madaniyah" },
  { id: "SR100", number: 100, name: "Al-Adiyat", totalAyat: 11, type: "Makkiyah" },
  { id: "SR101", number: 101, name: "Al-Qari'ah", totalAyat: 11, type: "Makkiyah" },
  { id: "SR102", number: 102, name: "At-Takathur", totalAyat: 8, type: "Makkiyah" },
  { id: "SR103", number: 103, name: "Al-Asr", totalAyat: 3, type: "Makkiyah" },
  { id: "SR104", number: 104, name: "Al-Humazah", totalAyat: 9, type: "Makkiyah" },
  { id: "SR105", number: 105, name: "Al-Fil", totalAyat: 5, type: "Makkiyah" },
  { id: "SR106", number: 106, name: "Quraish", totalAyat: 4, type: "Makkiyah" },
  { id: "SR107", number: 107, name: "Al-Ma'un", totalAyat: 7, type: "Makkiyah" },
  { id: "SR108", number: 108, name: "Al-Kautsar", totalAyat: 3, type: "Makkiyah" },
  { id: "SR109", number: 109, name: "Al-Kafirun", totalAyat: 6, type: "Makkiyah" },
  { id: "SR110", number: 110, name: "An-Nashr", totalAyat: 3, type: "Madaniyah" },
  { id: "SR111", number: 111, name: "Al-Masad", totalAyat: 5, type: "Makkiyah" },
  { id: "SR112", number: 112, name: "Al-Ikhlas", totalAyat: 4, type: "Makkiyah" },
  { id: "SR113", number: 113, name: "Al-Falaq", totalAyat: 5, type: "Makkiyah" },
  { id: "SR114", number: 114, name: "An-Nas", totalAyat: 6, type: "Makkiyah" }
];

export interface JuzData {
  number: number;
  name: string;
  description: string;
}

export const QURAN_JUZS: JuzData[] = Array.from({ length: 30 }, (_, i) => ({
  number: i + 1,
  name: `Juz ${i + 1}`,
  description: i === 29 ? "Juz Amma (Juz Akhir)" : `Bagian Juz ke-${i + 1} Al-Qur'an`
}));
